CXXFLAGS= -I$(PREFIX)/include -O3 -pedantic -g -std=c++17 -Wall -I..
LDFLAGS = -L$(PREFIX)/lib -ltermcapparser -L/usr/lib -lgmock -lgtest -lpthread
OBJECTS = test.o cell.o state.o termcapparser.o

all: test runtest

.PHONY:
runtest: test
	mkdir -p ../logs
	LD_LIBRARY_PATH=$(PREFIX)/lib:${LD_LIBRARY_PATH} ./test --gtest_output=xml:../logs/tests-linux.xml

.PHONY:
clean:
	rm -f $(OBJECTS) test

test: $(OBJECTS)
	$(CXX) -o test $(OBJECTS) $(LDFLAGS)

%.o: %.cc
	$(CXX) -c -o $@ $< $(CXXFLAGS)
